### ISSUE TITLE
nitpicks from roomSubTypes.d.ts 

### ISSUE THREAD

**Issue by epfly6** [IsaacScript/isaac-typescript-definitions#44]
[Clutch/The Possessor is finished](https://github.com/IsaacScript/isaac-typescript-definitions/blob/1cd7f86f0fc3203c25b01e7d92594471ba500cf0/typings/unofficial/enums/roomSubTypes.d.ts#L164-L165)

[MINESHAFT_ROOM_POST_CHASE is supposed to be equal to 31](https://github.com/IsaacScript/isaac-typescript-definitions/blob/1cd7f86f0fc3203c25b01e7d92594471ba500cf0/typings/unofficial/enums/roomSubTypes.d.ts#L322)

**Comment by Zamiell** [comment]
thanks!

**Comment by epfly6** [comment]
> can you submit a pr?

sure!
